<?php

namespace Backend\PoiBundle\Entity;

/**
 * PoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoiRepository extends \Doctrine\ORM\EntityRepository
{
}
