<?php

namespace Backend\AdministracyjneBundle\Entity;

use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresRepository extends EntityRepository {

    public function getFullname($id) {
	$em = $this->getEntityManager();
	$result = null;
	try {
	    $searchName = mb_strtolower($searchName, "UTF-8");
	    $query = $em->createQuery(
			    "SELECT m.id, m.nazwa, m.nazwa_gmi as gmina, m.nazwa_pow as powiat FROM BackendAdresyBundle:AdresTeryt m "
			    . "WHERE m.id = :id")->setParameter("id", $id)->getResult();

	    if (count($query) > 0) {
		$m = $query[0];
		$result = sprintf("%s (gm. %s) (pow. %s)", $m['nazwa'], $m['gmina'], $m['powiat']);
	    }
	} catch (\Exception $e) {
	    throw new \Exception($e);
	}

	return $result;
    }

}
