services:
    frontend.poi.poi_extension:
        class: Frontend\PoiBundle\Twig\PoiExtension
        public: true
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }
